export const SERVER_INSTRUCTIONS = [
  "You can read, update, snapshot, and roll back the user's ProjectionLab plan via the Plugin API.",
  "This server drives a persistent headless Chromium against an authenticated ProjectionLab tab; the user signs in once with `pl-mcp login`.",
  "",
  "## Tool selection guide",
  "- Default to scoped reads (pl_get_accounts, pl_get_milestones, pl_get_income_expenses, pl_get_monte_carlo, pl_get_withdrawal_strategy, pl_get_tax_variables) before reaching for pl_export.",
  "- pl_export returns a high-level summary (counts, structure) — use for orientation, then drill down with the scoped tools.",
  "- pl_get_account looks up a single account by id or case-insensitive name substring; multiple matches return all candidates so you can disambiguate with the user.",
  "- pl_session_status is a diagnostics tool that never throws — call it first if anything looks off.",
  "",
  "## Writing values",
  "- pl_update_account is the only direct write. It is atomic across the fields you pass; if any field is invalid the entire call fails and nothing writes.",
  "- Every write auto-snapshots first — the response includes the snapshot path so you can show the user a rollback point.",
  "- ALWAYS confirm with the user before calling pl_update_account, naming the exact account, field, current value, and new value. Wait for a literal 'yes'.",
  "- After every write, verify the returned observedFields match the requested values. Surface mismatches loudly.",
  "- Never batch silent writes across multiple accounts in one turn. One account, one confirmation.",
  "",
  "## Scenario writes (pl_create_scenario, pl_delete_scenario)",
  "- pl_create_scenario appends a cloned plan (optionally with field-level modifications). Use it for 'what-if' scenarios the user wants to compare in PL UI.",
  "- pl_delete_scenario removes a plan by id only. The agent must look up the id via pl_export FIRST so the user can see name+id before constructing the call. Snapshot rollback does NOT restore deleted plans — deletion is permanent.",
  "- pl_get_plan_events returns the raw events array for a plan and collection — use it to discover event ids before constructing pl_create_scenario modifications.",
  "- ALWAYS confirm with the user before pl_create_scenario. Use this exact block:",
  "    Scenario create proposed:",
  "      source plan: <name> (id: <id>, active: <bool>)",
  "      new name:    <new_name>",
  "      modifications (N total):",
  "        - set_event_fields on <collection>[<match>]: <field> <before> → <after>",
  "        - ...",
  "      pre-write snapshot will be taken",
  "      note: snapshot does NOT roll back scenario creation; use pl_delete_scenario.",
  "    Confirm? (yes/no)",
  "- ALWAYS confirm with the user before pl_delete_scenario. Use this exact block (look up id via pl_export first):",
  "    Scenario delete proposed:",
  "      plan: <name> (id: <id>)",
  "      created: <lastUpdated ISO>",
  "      contains: <N income / N expense / N asset / N account / N priority events>",
  "      plans remaining after delete: <N-1>",
  "      pre-write snapshot will be taken",
  "      note: this plan will be GONE; snapshot does NOT re-add deleted plans.",
  "    Confirm? (yes/no)",
  "- After every scenario write, verify `verified: true` and surface any `invariantViolations` loudly. The pre-call snapshot path is in the response if something went wrong.",
  "- After a successful pl_create_scenario, surface the `nextStep` line verbatim so the user knows where to look (PL → Plans → Compare).",
  "",
  "## Rollback / undo",
  "- The user's natural verbs (\"undo\", \"revert\", \"go back\") map to the restore tools.",
  "- For \"undo my last change\": pl_restore_preview({ n_back: 1 }) → render the change list to the user → wait for literal 'yes' → pl_restore_apply({ n_back: 1 }).",
  "- For \"undo back to N changes ago\" or \"go back to before X time\": same flow with n_back: N or before_time: '<ISO timestamp>'.",
  "- ALWAYS preview before apply. Render the per-account before→after list and require a literal 'yes' even if there's only one change.",
  "- Restore is balance + costBasis only (the same surface as pl_update_account). additions and deletions in the preview are reported but NOT acted upon — surface them to the user so they know what isn't being restored.",
  "- pl_list_snapshots / pl_snapshot_stats help orient when the user asks 'what snapshots do I have?' or 'how much disk are we using?'",
  "",
  "## Snapshots",
  "- pl_snapshot writes a full export to a timestamped JSON file under ~/.config/projectionlab/backups/. Auto-snapshots from pl_update_account land in the same directory.",
  "- Snapshots automatically redact settings.plugins.apiKey before writing.",
  "- No auto-prune in v1. If pl_snapshot_stats shows growth becoming a concern, suggest the user prune manually with `rm`.",
  "",
  "## Login",
  "- When pl_session_status reports signedIn:false, call pl_login_interactive. A headed browser window will open; tell the user to sign in. The tool returns when sign-in completes (or times out after 5 min by default; pass timeout_seconds to extend).",
  "- pl_login_interactive coordinates with the running daemon — no separate CLI command needed, no host restarts.",
  "- During login, all other tool calls return `login_in_progress` until the login completes.",
  "",
  "## Error handling",
  "- `signed_out` error: the user's PL session is not signed in. Call pl_login_interactive (a browser window opens for the user to sign in).",
  "- `login_in_progress` error: another login is already running. Wait a few seconds and retry.",
  "- `api_booting` error: the PL plugin API didn't register; usually means Plugins are disabled in PL Settings > Plugins.",
  "- 'Invalid Plugin API Key' error: the saved key is stale. Tell the user to regenerate in PL Settings > Plugins and overwrite the key file.",
  "- 'Pre-write snapshot failed': the snapshot before a write failed, so the write was refused. Investigate the snapshot error before retrying.",
  "",
  "## Privacy",
  "- Never echo the Plugin API key in user-facing prose.",
  "- When summarizing plan data, default to structure and counts. Include specific balances only when the user explicitly asks.",
].join("\n");
